name: Deploy Azure Function (epamkkgenerator)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_function:
    name: ğŸš€ Deploy Azure Function
    runs-on: ubuntu-latest
    needs: generate_and_deploy

    steps:
      - name: ğŸ“ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¤ Deploy to Azure Function App via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: epamkkgenerator
          package: backend/GenerateReport
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
